### PR TITLE
Update to Rust Nightly 2016-04-11

### PR DESCRIPTION
**Pull request by killercup**
Hey, I just wanted to get it to compile. Seemed like an easy fix :smile:

### CODE REVIEW

**Comment by killercup** [comment]
I couldn't run the tests locally, but I'm pretty sure I messed something up with rustup ("can't find crate for `std`" during `cargo run`). I think I've had these issues before and it was something with dyld's path…

**Comment by tsion** [comment]
@killercup Check out the instructions I added to the README recently - you need to set `--sysroot` currently. If you can compile and run some tests, would you mind also changing the references to 2016-04-05 in the README to 2016-04-11?

Thanks!

**Comment by killercup** [comment]
Okay, so I got the tests to work with this:

```bash
$ multirust run nightly cargo run -- \
    --sysroot $HOME/.multirust/toolchains/nightly-x86_64-apple-darwin/ \
    test/arrays.rs
```

but that path seems specific to `rustup` (the same command works with `rustup` instead of `multirust` as well).

I don't have the time tight now, but I'll update the Readme with more information tomorrow.

Do you have a script to run all the tests? Or, do your have any plans to use travis or something similar? (I can make a PR for that as well if you like.)

**Comment by tsion** [comment]
> but that path seems specific to rustup (the same command works with rustup instead of multirust as well).

Essentially, I think the path should point to the sysroot for whatever compiler you are compiling Miri with.

> I don't have the time tight now, but I'll update the Readme with more information tomorrow.

Thanks.

> Do you have a script to run all the tests? Or, do your have any plans to use travis or something similar? (I can make a PR for that as well if you like.)

I don't, currently. The tests aren't really tests yet, since nothing is checking their output. Adding an actual, automated test suite is high on my to-do list, but I welcome any help!

**Comment by killercup** [comment]
Updated the readme, I'll fiddle with running the tests on travis a bit.

**Comment by tsion** [comment]
Thanks!

**Pull request merged**
